version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create-tables.sql